- hosts: all
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
      loop:
        - ca-certificates
        - curl
        - openssh-server
        - postfix
        - rsync
        - tzdata
      become: yes

    - name: Download installation script
      get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
        dest: /tmp/

    - name: Run installation script
      command: bash /tmp/script.deb.sh
      become: yes

    - name: Install Gitlab CE
      apt:
        name: "{{ item }}"
      loop:
        - gitlab-ce
      become: yes

    - name: Configure gitlab.rb
      replace:
        path: /etc/gitlab/gitlab.rb
        regexp: "^external_url 'http://gitlab.example.com'"
        replace: external_url 'http://127.0.0.1'
      become: yes

    - name: Configure Gitlab backup path
      replace:
        path: /etc/gitlab/gitlab.rb
        regexp: "^#0gitlab_rails['manage_backup_path'] = true"
        replace: gitlab_rails['manage_backup_path'] = true
      become: yes

#    - name: Configure Gitlab manage backup
#      replace:
#        path: /etc/gitlab/gitlab.rb
#        regexp: '# gitlab_rails['backup_path'] = "/var/opt/gitlab/backups"'
#        replace: gitlab_rails['backup_path'] = "/var/opt/gitlab/backups"
#      become: yes

    - name: Reconfigure Gitlab
      command: gitlab-ctl reconfigure
      become: yes