- hosts: kubernetes
  tasks:
    - name: Set timezone To Europe/Moscow
      timezone:
        name: Europe/Moscow

    - name: Add machines to hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - 10.0.1.150 kubemaster

    - name: Disable swapoff
      shell: swapoff -a

    - name: Disable swap at fstab file
      replace:
        path: /etc/fstab
        regexp: "^/swap"
        replace: "#/swap"

    - name: Install required packages
      apt:
        name: "{{ item }}"
      loop:
        - python-apt
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add an Docker Apt signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker CE repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: "{{ item }}"
      loop:
        - docker-ce=18.06.2~ce~3-0~ubuntu
#        - docker.io
#        - docker-ce
#        - docker-ce-cli
#        - containerd.io

    - name: Add an Kubernetes Apt signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Disable nftables if it used
      shell: "{{ item }}"
      loop:
        - update-alternatives --set iptables /usr/sbin/iptables-legacy
        - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
        - update-alternatives --set arptables /usr/sbin/arptables-legacy
        - update-alternatives --set ebtables /usr/sbin/ebtables-legacy
      ignore_errors: yes

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        update_cache: yes

    - name: Install kubelet, kubeadm and kubectl
      apt:
        name: "{{ item }}"
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Disable update of kubelet, kubeadm, kubectl packages
      shell: "apt-mark hold {{ item }}"
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Create user kubeadmin on all nodes
      user:
        name: kubeadmin
        comment: Kubernetes user
        groups: sudo, docker
        append: yes
        shell: /bin/bash
        home: /home/kubeadmin
        create_home: yes

    - name: Change sudo settings to NOPASSWD
      lineinfile:
        dest: /etc/sudoers
        line: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'
