- hosts: kubemaster
  tasks:
    - name: Init Kubernetes cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 > cluster_initialized.txt

    - name: Create .kube directory
      become: yes
      become_user: kubeadmin
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kubeadmin/.kube/config
        remote_src: yes
        owner: kubeadmin

    - name: Install Pod network
      become: yes
      become_user: kubeadmin
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/32a765fd19ba45b387fdc5e3812c41fff47cfd55/Documentation/kube-flannel.yml > pod_network_setup.txt
