- hosts: kubemaster
  become: yes
  become_user: kubeadmin
  tasks:
    - name: Copy {{ deploy }} deployment file
      copy:
        src: deployments/{{ deploy }}.yml
        dest: /tmp/

    - name: Deploy {{ deploy }}
      shell: kubectl apply -f /tmp/{{ deploy }}.yml